openapi: 3.0.0
info:
  title: 'Sample API '
  description: |
    Sample API to demostrate API varietes feature in CI pipeline.

    Standard API.

    Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 1.1.10
servers:
- url: "{serverRoot}/sample/v1"
  variables:
    serverRoot:
      default: https://extenal-lb-ip-of-scef-bm-traffic:27900
tags:
- name: default
security:
- ApiKeyAuth: []
- BasicAuth: []
paths:
  /config:
    put:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NotificationEventConfigRequest'
      responses:
        "200":
          description: OK
  /something/{id}:
    put:
      tags:
      - default
      summary: Update something.
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          example: "{raw-string}"
        examples:
          raw:
            summary: raw string
            value: "{raw-string}"
          encoded:
            summary: URL encoded
            value: "%7Braw-string%7D"
      - $ref: '#/components/parameters/partnerId'
      - name: type
        in: query
        description: Type is an extensible enum
        schema:
          anyOf:
          - type: string
            title: enum
            enum:
            - foo
            - bar
          - type: string
            title: reserved
            description: | # Don't omit this description
              Reserved for forward-compatibility with future extensions to the enumeration.
      - name: created
        in: query
        schema:
          example: "2020-4-17"
          anyOf:
          - $ref: '#/components/schemas/DateTime'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                tree:
                  $ref: '#/components/schemas/Node'
                area:
                  allOf:
                  - $ref: '#/components/schemas/GeographicArea__common'
                  - description: "Add description"
      responses:
        "200":
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    ApiKeyAuth:
      type: apiKey
      in: header
      name: API-Key
  parameters:
    partnerId:
      name: partnerId
      in: header
      description: Example of using `x-conditional-exclude` to define header added by API GW.
      schema:
        type: string
  schemas:
    DateTime:
      type: string
      example: 2019-09-11T08:33:24.984000Z
    Node:
      type: object
      properties:
        value:
          type: number
        name:
          type: string
        children:
          type: array
          items:
            $ref: '#/components/schemas/Node'
    NotificationEventConfigRequest:
      description: Specifies request of the configuration.
      type: object
      properties:
        configMode:
          $ref: '#/components/schemas/ConfigMode'
      oneOf:
      - required:
        - eventSettings
        properties:
          ConfigMode:
            enum:
            - CUSTOMIZE
          eventSettings:
            $ref: '#/components/schemas/EventSettings'
      - required:
        - configMode
        properties:
          configMode:
            enum:
            - PARTNER
            - OFF
    ConfigMode:
      description: Specifies notification config mode.
      anyOf:
      - type: string
        title: enum
        enum:
        - CUSTOMIZE
        - PARTNER
        - DEVICE
        - OFF
        default: CUSTOMIZE
      - type: string
        title: reserved
        description: | # Don't omit this description
          Reserved for forward-compatibility with future extensions to the enumeration.
      type: string
    EventSettings:
      description: Specifies detail event configurations, only required in request and show in response if configMode is CUSTOMIZE, otherwise will be ignored in request and not in response.
      type: object
    SupportedGADShapes__common:
      anyOf:
      - type: string
        enum:
        - POINT
        - POINT_ALTITUDE
        description: |
          The suported GAD shapes are as the following:
          * POINT - means the shape responded to SCS/AS is Point.
          * POINT_ALTITUDE - means the shape responded to SCS/AS is PointAltitude.
      - type: string
    GeographicalCoordinates__common:
      type: object
      required:
      - lon
      - lat
      properties:
        lon:
          type: number
          format: float
          minimum: -180
          maximum: 180
        lat:
          type: number
          format: float
          minimum: -90
          maximum: 90
    Altitude__common:
      type: number
      format: float
      minimum: -32767
      maximum: 32767
    PointAltitude__common:
      allOf:
      - $ref: '#/components/schemas/GADShape__common'
      - type: object
        required:
        - point
        - altitude
        properties:
          point:
            $ref: '#/components/schemas/GeographicalCoordinates__common'
          altitude:
            $ref: '#/components/schemas/Altitude__common'
    GADShape__common:
      type: object
      required:
      - shape
      properties:
        shape:
          $ref: '#/components/schemas/SupportedGADShapes__common'
      discriminator:
        propertyName: shape
        mapping:
          POINT: '#/components/schemas/Point__common'
          POINT_ALTITUDE: '#/components/schemas/PointAltitude__common'
    Point__common:
      allOf:
      - $ref: '#/components/schemas/GADShape__common'
      - type: object
        required:
        - point
        properties:
          point:
            $ref: '#/components/schemas/GeographicalCoordinates__common'
    GeographicArea__common:
      anyOf:
      - $ref: '#/components/schemas/Point__common'
      - $ref: '#/components/schemas/PointAltitude__common'
